### PR TITLE
add: new base64 based challenge

### PR DESCRIPTION
**Pull request by aashu10sh**
## Description of changes

This pull request introduces a new challenge class `BasicChallenge` in the `challenges/basic-challenge/index.php` file. The class is designed to hold logic for the 'basic-challenge' challenge.
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/lennis-dev/hackit/blob/master/CONTRIBUTING.md)
- [x] I don't have any breaking changes
- [x] I have tested the changes
- [x] I have asked in the [Disscussion](https://github.com/lennis-dev/hackit/discussions) if the changes are wanted or needed.

## Additional information

...

## Reviewers

@lennis-dev

---

Add a :+1: **reaction** to [pull requests and issues you find important](https://github.com/lennis-dev/hackit/issues?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Review by lennis-dev — CHANGES_REQUESTED** [review]
Good work but you need to sign off your commit with the [DCO](https://developercertificate.org/) as specified in CONTRIBUTING.md
https://github.com/lennis-dev/hackit/blob/604b453402c377fdfde7350a49d41ae14babdbf2/CONTRIBUTING.md?plain=1#L20-L25

**Comment by aashu10sh** [comment]
@lennis-dev Done!

**Comment by lennis-dev** [comment]
> @lennis-dev Done!

Not quite now you have signed off a new commit, revert the new one and then execute `git commit --amend --signoff` to sign off the old commit

**Comment by aashu10sh** [comment]
@lennis-dev It should be done now, Thank you for being patient.

**Review by lennis-dev — APPROVED** [review]
So, now everything fits, thank you for your contribution and congratulations on your first open source contribution :tada:, close #32

**Pull request merged**
